version: 2
orbs:
  cypress: cypress-io/cypress@1.22.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "79:ac:b1:fb:d7:4f:6a:3b:9e:aa:d8:bc:81:ac:ec:e7"
      - checkout
      - run:
          name: Push Frontend to Production
          command: |
            git push git@github.com:neethu-ms/journalling_app.git deploy/frontend-nms:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build