version: 2
orbs:
  cypress: cypress-io/cypress@1.22.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "89:fa:db:e1:54:e9:61:38:e0:3c:d9:9c:37:f4:dd:a7"
      - checkout
      - run:
          name: Push Frontend to Production
          command: |
            git push git@github.com:neethu-ms/journalling_app.git deploy/frontend-nms:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build